[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
op_sepolia = "https://sepolia.optimism.io"
rise_sepolia = "https://testnet.riselabs.xyz"
arb_sepolia = "https://arbitrum-sepolia.drpc.org"
cachain_sepolia = "http://127.0.0.1:8547/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
